import 'server-only';
import { z } from 'zod';

const schema = z.object({
  NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: z.string().min(20),
  SUPABASE_SECRET_KEY: z.string().min(20),
  SUPABASE_DB_URL: z.string().url(),
  ADPORT_DB_ROLE: z.string().regex(/^[a-z_][a-z0-9_]*$/).default('adport_backend'),
  ADPORT_CLOUD_BASE_URL: z.string().url(),
  ADPORT_CLOUD_ENCRYPTION_KEY: z.string().min(40),
  ADPORT_API_KEY_PEPPER: z.string().min(32),
  // Independent HMAC key for short-lived MCP OAuth access tokens.
  ADPORT_MCP_OAUTH_SIGNING_KEY: z.string().min(40),
  STRIPE_SECRET_KEY: z.string().regex(/^(?:sk|rk)_(?:test|live)_/).optional(),
  STRIPE_WEBHOOK_SECRET: z.string().startsWith('whsec_').optional(),
  STRIPE_OPERATOR_PRICE_ID: z.string().startsWith('price_').optional(),
  STRIPE_AGENCY_PRICE_ID: z.string().startsWith('price_').optional(),
  // Set to the exact token generated by the OpenAI plugin submission portal.
  OPENAI_APPS_CHALLENGE_TOKEN: z.string().min(1).optional(),
  // Adport-owned Google Ads OAuth application (verified project).
  GOOGLE_ADS_CLIENT_ID: z.string().min(10).optional(),
  GOOGLE_ADS_CLIENT_SECRET: z.string().min(8).optional(),
  GOOGLE_ADS_DEVELOPER_TOKEN: z.string().min(8).optional(),
  GOOGLE_ADS_LOGIN_CUSTOMER_ID: z.string().regex(/^\d{10}$/).optional(),
  GOOGLE_OAUTH_TOKEN_URL: z.string().url().default('https://oauth2.googleapis.com/token'),
  GOOGLE_OAUTH_REVOKE_URL: z.string().url().default('https://oauth2.googleapis.com/revoke'),
  // Adport-owned Meta Marketing API app (Facebook Login for Business).
  META_APP_ID: z.string().min(5).optional(),
  META_APP_SECRET: z.string().min(8).optional(),
  META_LOGIN_CONFIG_ID: z.string().min(5).optional(),
  META_API_VERSION: z.string().regex(/^v\d+\.\d+$/).optional(),
  // Adport-owned TikTok for Business Marketing API app.
  TIKTOK_APP_ID: z.string().min(5).optional(),
  TIKTOK_APP_SECRET: z.string().min(8).optional(),
  // Adport-owned Microsoft Entra application + Microsoft Advertising developer token.
  MICROSOFT_ADS_CLIENT_ID: z.string().min(8).optional(),
  MICROSOFT_ADS_CLIENT_SECRET: z.string().min(8).optional(),
  MICROSOFT_ADS_DEVELOPER_TOKEN: z.string().min(8).optional(),
  // Adport-owned Reddit Ads API web app.
  REDDIT_CLIENT_ID: z.string().min(5).optional(),
  REDDIT_CLIENT_SECRET: z.string().min(8).optional(),
  REDDIT_USER_AGENT: z.string().min(5).optional(),
  // Adport-owned Apple Ads service-provider OAuth client.
  APPLE_ADS_CLIENT_ID: z.string().regex(/^SEARCHADS\.[0-9a-f-]+$/i).optional(),
  APPLE_ADS_TEAM_ID: z.string().regex(/^SEARCHADS\.[0-9a-f-]+$/i).optional(),
  APPLE_ADS_KEY_ID: z.string().uuid().optional(),
  APPLE_ADS_PRIVATE_KEY: z.string().min(100).optional(),
});

export type CloudEnv = z.infer<typeof schema>;
export type GoogleCloudEnv = CloudEnv & {
  GOOGLE_ADS_CLIENT_ID: string;
  GOOGLE_ADS_CLIENT_SECRET: string;
  GOOGLE_ADS_DEVELOPER_TOKEN: string;
};

let parsed: CloudEnv | undefined;

export function env(): CloudEnv {
  parsed ??= schema.parse(process.env);
  return parsed;
}

export function googleEnv(): GoogleCloudEnv {
  const value = env();
  if (!value.GOOGLE_ADS_CLIENT_ID || !value.GOOGLE_ADS_CLIENT_SECRET || !value.GOOGLE_ADS_DEVELOPER_TOKEN) {
    throw new Error('Google Ads cloud OAuth is not configured. Set GOOGLE_ADS_CLIENT_ID, GOOGLE_ADS_CLIENT_SECRET, and GOOGLE_ADS_DEVELOPER_TOKEN.');
  }
  return value as GoogleCloudEnv;
}

export function resetEnvForTests(): void {
  parsed = undefined;
}
